# =============================================================================
# Auto-generated by serverless-rds-automation
# Requested at : 2026-06-08T17:33:51.891852+00:00
#
# DO NOT EDIT MANUALLY — re-provisioning will overwrite this file.
# To change cluster settings open a manual PR and update this file directly.
# =============================================================================

module "rds_analytics_db" {
  source = "../terraform-modules/rds-cluster"

  cluster_identifier = "analytics-db"
  environment        = "dev"
  engine             = "postgres"
  database_name      = "analytics-db"
  master_username    = "dbadmin"

  # These variables must be defined in clusters/variables.tf
  vpc_id     = var.vpc_id
  subnet_ids = var.subnet_ids

  # Allow the Lambda execution SG inbound access to this cluster.
  # The SG ID is exported by the SAM template (LambdaSecurityGroupId).
  allowed_security_group_ids = var.allowed_security_group_ids

  tags = {
    AutoProvisioned = "true"
    RequestedAt     = "2026-06-08T17:33:51.891852+00:00"
  }
}

output "analytics_db_cluster_endpoint" {
  description = "Writer endpoint for the analytics-db cluster"
  value       = module.rds_analytics_db.cluster_endpoint
}

output "analytics_db_reader_endpoint" {
  description = "Reader endpoint for the analytics-db cluster"
  value       = module.rds_analytics_db.cluster_reader_endpoint
}

output "analytics_db_secret_arn" {
  description = "Secrets Manager ARN holding analytics-db DB credentials"
  value       = module.rds_analytics_db.secret_arn
  sensitive   = true
}
