# =============================================================================
# Auto-generated by serverless-rds-automation
# Requested at : 2026-06-08T17:29:54.183119+00:00
#
# DO NOT EDIT MANUALLY — re-provisioning will overwrite this file.
# To change cluster settings open a manual PR and update this file directly.
# =============================================================================

module "rds_esm_disabled_test" {
  source = "../terraform-modules/rds-cluster"

  cluster_identifier = "esm-disabled-test"
  environment        = "dev"
  engine             = "postgres"
  database_name      = "esm-disabled-test"
  master_username    = "dbadmin"

  # These variables must be defined in clusters/variables.tf
  vpc_id     = var.vpc_id
  subnet_ids = var.subnet_ids

  # Allow the Lambda execution SG inbound access to this cluster.
  # The SG ID is exported by the SAM template (LambdaSecurityGroupId).
  allowed_security_group_ids = var.allowed_security_group_ids

  tags = {
    AutoProvisioned = "true"
    RequestedAt     = "2026-06-08T17:29:54.183119+00:00"
  }
}

output "esm_disabled_test_cluster_endpoint" {
  description = "Writer endpoint for the esm-disabled-test cluster"
  value       = module.rds_esm_disabled_test.cluster_endpoint
}

output "esm_disabled_test_reader_endpoint" {
  description = "Reader endpoint for the esm-disabled-test cluster"
  value       = module.rds_esm_disabled_test.cluster_reader_endpoint
}

output "esm_disabled_test_secret_arn" {
  description = "Secrets Manager ARN holding esm-disabled-test DB credentials"
  value       = module.rds_esm_disabled_test.secret_arn
  sensitive   = true
}
