# =============================================================================
# Auto-generated by serverless-rds-automation
# Requested at : 2026-06-08T16:34:16.553480+00:00
#
# DO NOT EDIT MANUALLY — re-provisioning will overwrite this file.
# To change cluster settings open a manual PR and update this file directly.
# =============================================================================

module "rds_test_cluster" {
  source = "../terraform-modules/rds-cluster"

  cluster_identifier = "test-cluster"
  environment        = "dev"
  engine             = "postgres"
  database_name      = "test-cluster"
  master_username    = "dbadmin"

  # These variables must be defined in clusters/variables.tf
  vpc_id     = var.vpc_id
  subnet_ids = var.subnet_ids

  # Allow the Lambda execution SG inbound access to this cluster.
  # The SG ID is exported by the SAM template (LambdaSecurityGroupId).
  allowed_security_group_ids = var.allowed_security_group_ids

  tags = {
    AutoProvisioned = "true"
    RequestedAt     = "2026-06-08T16:34:16.553480+00:00"
  }
}

output "test_cluster_cluster_endpoint" {
  description = "Writer endpoint for the test-cluster cluster"
  value       = module.rds_test_cluster.cluster_endpoint
}

output "test_cluster_reader_endpoint" {
  description = "Reader endpoint for the test-cluster cluster"
  value       = module.rds_test_cluster.cluster_reader_endpoint
}

output "test_cluster_secret_arn" {
  description = "Secrets Manager ARN holding test-cluster DB credentials"
  value       = module.rds_test_cluster.secret_arn
  sensitive   = true
}
