terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5"
    }
  }
}

# ---------------------------------------------------------------------------
# Locals — all environment-based decisions live here, not scattered in resources
# ---------------------------------------------------------------------------
locals {
  # Aurora engine names and their default pinned versions
  engine_map = {
    mysql    = "aurora-mysql"
    postgres = "aurora-postgresql"
  }
  engine_version_map = {
    mysql    = "8.0.mysql_aurora.3.06.0"
    postgres = "16.2"
  }
  port_map = {
    mysql    = 3306
    postgres = 5432
  }

  # Environment-driven sizing: dev is cheap; prod is HA
  instance_class_map = {
    dev  = "db.t3.medium"   # Cheapest Aurora-compatible class
    prod = "db.r6g.large"   # Memory-optimised, Graviton2
  }
  # prod gets a reader instance for HA; dev is single-instance
  instance_count_map = {
    dev  = 1
    prod = 2
  }

  # Resolved shorthand used throughout
  aurora_engine   = local.engine_map[var.engine]
  engine_version  = local.engine_version_map[var.engine]
  db_port         = local.port_map[var.engine]
  instance_class  = local.instance_class_map[var.environment]
  instance_count  = local.instance_count_map[var.environment]
  is_prod         = var.environment == "prod"

  # CloudWatch log exports differ by engine
  log_exports = var.engine == "postgres" ? ["postgresql"] : ["audit", "error", "general", "slowquery"]

  secret_name = "${var.environment}/${var.cluster_identifier}/db-credentials"

  common_tags = merge(var.tags, {
    Environment = var.environment
    ManagedBy   = "Terraform"
    Module      = "rds-cluster"
    Cluster     = var.cluster_identifier
  })
}

# ---------------------------------------------------------------------------
# Password — generated by Terraform; never written in code
# ---------------------------------------------------------------------------
resource "random_password" "master" {
  length           = 32
  special          = true
  # Exclude characters that cause issues in connection strings or shell quoting
  override_special = "!#%&*()-_=+[]{}<>:?"
}

# ---------------------------------------------------------------------------
# Secrets Manager — store credentials before the cluster uses them
# ---------------------------------------------------------------------------
resource "aws_secretsmanager_secret" "db_credentials" {
  name        = local.secret_name
  description = "Master credentials for RDS cluster ${var.cluster_identifier} (${var.environment})"

  # prod: 30-day recovery window; dev: immediate deletion to avoid naming conflicts
  recovery_window_in_days = local.is_prod ? 30 : 0

  tags = local.common_tags
}

# The secret version is written AFTER the cluster exists so we can embed the
# live endpoint. Terraform's dependency graph resolves this automatically.
resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id

  secret_string = jsonencode({
    username = var.master_username
    password = random_password.master.result
    engine   = var.engine
    host     = aws_rds_cluster.this.endpoint
    port     = local.db_port
    dbname   = var.database_name
  })
}

# ---------------------------------------------------------------------------
# Networking — Subnet Group
# ---------------------------------------------------------------------------
resource "aws_db_subnet_group" "this" {
  name        = "${var.cluster_identifier}-${var.environment}"
  description = "Private subnets for ${var.cluster_identifier} (${var.environment})"
  subnet_ids  = var.subnet_ids

  tags = local.common_tags
}

# ---------------------------------------------------------------------------
# Networking — Security Group
# ---------------------------------------------------------------------------
resource "aws_security_group" "rds" {
  name        = "${var.cluster_identifier}-${var.environment}-rds"
  description = "Controls inbound access to RDS cluster ${var.cluster_identifier}"
  vpc_id      = var.vpc_id

  # Recreate before destroy to avoid downtime when name changes
  lifecycle {
    create_before_destroy = true
  }

  tags = local.common_tags
}

# Ingress from trusted security groups (e.g. Lambda execution role SG)
resource "aws_vpc_security_group_ingress_rule" "from_sg" {
  for_each = toset(var.allowed_security_group_ids)

  security_group_id            = aws_security_group.rds.id
  referenced_security_group_id = each.value
  from_port                    = local.db_port
  to_port                      = local.db_port
  ip_protocol                  = "tcp"
  description                  = "DB access from security group ${each.value}"

  tags = local.common_tags
}

# Ingress from explicit CIDRs (bastion / VPN — use sparingly)
resource "aws_vpc_security_group_ingress_rule" "from_cidr" {
  for_each = toset(var.allowed_cidr_blocks)

  security_group_id = aws_security_group.rds.id
  cidr_ipv4         = each.value
  from_port         = local.db_port
  to_port           = local.db_port
  ip_protocol       = "tcp"
  description       = "DB access from CIDR ${each.value}"

  tags = local.common_tags
}

# Explicit deny-all egress — RDS never initiates outbound connections
resource "aws_vpc_security_group_egress_rule" "deny_all" {
  security_group_id = aws_security_group.rds.id
  cidr_ipv4         = "127.0.0.1/32" # Effectively a no-op destination; blocks real egress
  from_port         = 0
  to_port           = 0
  ip_protocol       = "-1"
  description       = "No outbound traffic needed from RDS"

  tags = local.common_tags
}

# ---------------------------------------------------------------------------
# RDS Aurora Cluster
# ---------------------------------------------------------------------------
resource "aws_rds_cluster" "this" {
  cluster_identifier = "${var.cluster_identifier}-${var.environment}"
  engine             = local.aurora_engine
  engine_version     = local.engine_version
  port               = local.db_port

  database_name   = var.database_name
  master_username = var.master_username
  master_password = random_password.master.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.rds.id]

  # Encryption at rest — always on
  storage_encrypted = true

  # Prod: block accidental drops; dev: allow clean teardown
  deletion_protection = local.is_prod

  # Prod: take a final snapshot before destroy; dev: skip to speed up teardown
  skip_final_snapshot       = !local.is_prod
  final_snapshot_identifier = local.is_prod ? "${var.cluster_identifier}-${var.environment}-final" : null

  # Prod: 7-day PITR; dev: 1 day minimum
  backup_retention_period      = local.is_prod ? 7 : 1
  preferred_backup_window      = "03:00-04:00"
  preferred_maintenance_window = "mon:04:00-mon:05:00"

  enabled_cloudwatch_logs_exports = local.log_exports

  tags = local.common_tags

  # Password is managed by Secrets Manager after initial creation;
  # prevent Terraform from resetting it on every plan.
  lifecycle {
    ignore_changes = [master_password]
  }
}

# ---------------------------------------------------------------------------
# Cluster Instances
# count=1 in dev (writer only); count=2 in prod (writer + reader)
# ---------------------------------------------------------------------------
resource "aws_rds_cluster_instance" "this" {
  count = local.instance_count

  identifier           = "${var.cluster_identifier}-${var.environment}-${count.index}"
  cluster_identifier   = aws_rds_cluster.this.id
  instance_class       = local.instance_class
  engine               = aws_rds_cluster.this.engine
  engine_version       = aws_rds_cluster.this.engine_version
  db_subnet_group_name = aws_db_subnet_group.this.name

  # Never expose RDS directly to the internet
  publicly_accessible = false

  # Performance Insights on prod only (has an additional cost)
  performance_insights_enabled = local.is_prod

  tags = merge(local.common_tags, {
    Role = count.index == 0 ? "writer" : "reader"
  })
}
